import { getSession } from 'next-auth/react'
import Head from 'next/head'
import React from 'react'
import Content from '../components/Content'
import Player from '../components/Player'
import Sidebar from '../components/Sidebar'

const Home: React.FC = () => {
    return (
        <div className='bg-black h-screen overflow-hidden'>
            <Head>
                <meta charSet='utf-8' />
                <meta name="description" content="Generated by create next app" />

                <link rel="icon" href="/favicon.ico" />

                <title>Spotify</title>
            </Head>

            <main className='flex'>
                <Sidebar />
                <Content />
            </main>
            <div className='sticky bottom-0'>
                <Player />
            </div>
        </div>
    )
}

export default Home

export const getServerSideProps = async(context) => {
    const session = await getSession(context)

    return {
        props: {
            session
        }
    }
}


