import Head from 'next/head'
import React from 'react'
import Sidebar from '../components/Sidebar'

const Home: React.FC = () => {
    return (
        <div className='bg-black h-screen overflow-hidden'>
            <Head>
                <meta charSet='utf-8' />
                <meta name="description" content="Generated by create next app" />

                <link rel="icon" href="/favicon.ico" />

                <title>Spotify</title>
            </Head>

            <main>
                <Sidebar />
                {/* Content */}
            </main>

            <div>
                {/* Player */}
            </div>
        </div>
    )
}

export default Home
