import Head from 'next/head'
import React from 'react'

const Home: React.FC = () => {
    return(
        <div>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>
                    Hello World
                </h1>
            </main>
        </div>
    )
}

export default Home